name: 'CI pipeline for ECR image'

on:
    workflow_dispatch:
    
    push:
        branches:
            - main
        paths:
            - python-app

permissions:
    contents: read


jobs:

    deploy-ecr-images:
        runs-on: ubuntu-latest

        steps:

            - name: Copy Repo Code
              uses: actions/checkout@v4
            
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ vars.AWS_REGION }}
            
            - name: Login to ECR
              uses: aws-actions/amazon-ecr-login@v2
              id: login-ecr
            
            - name: Build, tag, and push docker image to Amazon ECR
              env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: ${{ vars.ECR_REPOSITORY_NAME }}
                IMAGE_TAG: ${{ github.sha }}
              run: |
                docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG